version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./docker/
      dockerfile: Dockerfile
    container_name: ksei-lou-api
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ksei-lou-api-network
  postgres:
    container_name: ksei-lou-api-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./docker/database/data/postgres:/data/postgres
      - ./docker/database/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - ksei-lou-api-network
  nginx:
    image: nginx:alpine
    container_name: ksei-lou-api-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - ksei-lou-api-network
networks:
  ksei-lou-api-network:
    driver: bridge
